[package]
name = "gsms-rust"
version = "0.0.1"
authors = ["Duncan Fryer"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openpty = "0.1.2"
